// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun.cnst;

public interface FUN_GET_SUBED_KEYWORDS
{
    String value = "GET_SUBED_KEYWORDS";
}
