// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce.cnst;

public interface ACCOUNT_TYPE_QQ
{
    int value = 1;
}
