// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce.cnst;

public interface CODE_IDENTITY_ILLEGAL
{
    int value = -3;
}
