// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ClientNewsContent extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ClientNewsContent";
    }

    public String fullClassName()
    {
        return "zhi_xun.ClientNewsContent";
    }

    public int id = 0;

    public String content = "";

    public java.util.ArrayList<String> imgs = null;

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public java.util.ArrayList<String> getImgs()
    {
        return imgs;
    }

    public void  setImgs(java.util.ArrayList<String> imgs)
    {
        this.imgs = imgs;
    }

    public ClientNewsContent()
    {
    }

    public ClientNewsContent(int id, String content, java.util.ArrayList<String> imgs)
    {
        this.id = id;
        this.content = content;
        this.imgs = imgs;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ClientNewsContent t = (ClientNewsContent) o;
        return (
            com.qq.taf.jce.JceUtil.equals(id, t.id) && 
            com.qq.taf.jce.JceUtil.equals(content, t.content) && 
            com.qq.taf.jce.JceUtil.equals(imgs, t.imgs) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != content)
        {
            _os.write(content, 1);
        }
        if (null != imgs)
        {
            _os.write(imgs, 2);
        }
    }

    static java.util.ArrayList<String> cache_imgs;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (int) _is.read(id, 0, true);
        this.content =  _is.readString(1, false);
        if(null == cache_imgs)
        {
            cache_imgs = new java.util.ArrayList<String>();
            String __var_3 = "";
            ((java.util.ArrayList<String>)cache_imgs).add(__var_3);
        }
        this.imgs = (java.util.ArrayList<String>) _is.read(cache_imgs, 2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(content, "content");
        _ds.display(imgs, "imgs");
    }

}

