// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ClientNewsCategoryHolder
{
    public ClientNewsCategoryHolder()
    {
    }
    public ClientNewsCategoryHolder(ClientNewsCategory value)
    {
        this.value = value;
    }

    public ClientNewsCategory value;
}
