// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ClientNewsCategory extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ClientNewsCategory";
    }

    public String fullClassName()
    {
        return "zhi_xun.ClientNewsCategory";
    }

    public int id = 0;

    public String name = "";

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public ClientNewsCategory()
    {
    }

    public ClientNewsCategory(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ClientNewsCategory t = (ClientNewsCategory) o;
        return (
            com.qq.taf.jce.JceUtil.equals(id, t.id) && 
            com.qq.taf.jce.JceUtil.equals(name, t.name) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != name)
        {
            _os.write(name, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (int) _is.read(id, 0, true);
        this.name =  _is.readString(1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(name, "name");
    }

}

