// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ReqGetSubedKeywords extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ReqGetSubedKeywords";
    }

    public String fullClassName()
    {
        return "zhi_xun.ReqGetSubedKeywords";
    }

    public zhi_xun.SessionInfo sessionInfo = null;

    public zhi_xun.SessionInfo getSessionInfo()
    {
        return sessionInfo;
    }

    public void  setSessionInfo(zhi_xun.SessionInfo sessionInfo)
    {
        this.sessionInfo = sessionInfo;
    }

    public ReqGetSubedKeywords()
    {
    }

    public ReqGetSubedKeywords(zhi_xun.SessionInfo sessionInfo)
    {
        this.sessionInfo = sessionInfo;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqGetSubedKeywords t = (ReqGetSubedKeywords) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sessionInfo, t.sessionInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != sessionInfo)
        {
            _os.write(sessionInfo, 0);
        }
    }

    static zhi_xun.SessionInfo cache_sessionInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_sessionInfo)
        {
            cache_sessionInfo = new zhi_xun.SessionInfo();
        }
        this.sessionInfo = (zhi_xun.SessionInfo) _is.read(cache_sessionInfo, 0, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sessionInfo, "sessionInfo");
    }

}

