// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ReqGetSubedKeywordsHolder
{
    public ReqGetSubedKeywordsHolder()
    {
    }
    public ReqGetSubedKeywordsHolder(ReqGetSubedKeywords value)
    {
        this.value = value;
    }

    public ReqGetSubedKeywords value;
}
