// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ReqSubKeywords extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ReqSubKeywords";
    }

    public String fullClassName()
    {
        return "zhi_xun.ReqSubKeywords";
    }

    public zhi_xun.SessionInfo sessionInfo = null;

    public java.util.ArrayList<String> keywords = null;

    public zhi_xun.SessionInfo getSessionInfo()
    {
        return sessionInfo;
    }

    public void  setSessionInfo(zhi_xun.SessionInfo sessionInfo)
    {
        this.sessionInfo = sessionInfo;
    }

    public java.util.ArrayList<String> getKeywords()
    {
        return keywords;
    }

    public void  setKeywords(java.util.ArrayList<String> keywords)
    {
        this.keywords = keywords;
    }

    public ReqSubKeywords()
    {
    }

    public ReqSubKeywords(zhi_xun.SessionInfo sessionInfo, java.util.ArrayList<String> keywords)
    {
        this.sessionInfo = sessionInfo;
        this.keywords = keywords;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqSubKeywords t = (ReqSubKeywords) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sessionInfo, t.sessionInfo) && 
            com.qq.taf.jce.JceUtil.equals(keywords, t.keywords) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != sessionInfo)
        {
            _os.write(sessionInfo, 0);
        }
        if (null != keywords)
        {
            _os.write(keywords, 1);
        }
    }

    static zhi_xun.SessionInfo cache_sessionInfo;
    static java.util.ArrayList<String> cache_keywords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_sessionInfo)
        {
            cache_sessionInfo = new zhi_xun.SessionInfo();
        }
        this.sessionInfo = (zhi_xun.SessionInfo) _is.read(cache_sessionInfo, 0, false);
        if(null == cache_keywords)
        {
            cache_keywords = new java.util.ArrayList<String>();
            String __var_7 = "";
            ((java.util.ArrayList<String>)cache_keywords).add(__var_7);
        }
        this.keywords = (java.util.ArrayList<String>) _is.read(cache_keywords, 1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sessionInfo, "sessionInfo");
        _ds.display(keywords, "keywords");
    }

}

