// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ReqUserLogin extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ReqUserLogin";
    }

    public String fullClassName()
    {
        return "zhi_xun.ReqUserLogin";
    }

    public String account = "";

    public String password = "";

    public int accountType = 0;

    public String getAccount()
    {
        return account;
    }

    public void  setAccount(String account)
    {
        this.account = account;
    }

    public String getPassword()
    {
        return password;
    }

    public void  setPassword(String password)
    {
        this.password = password;
    }

    public int getAccountType()
    {
        return accountType;
    }

    public void  setAccountType(int accountType)
    {
        this.accountType = accountType;
    }

    public ReqUserLogin()
    {
    }

    public ReqUserLogin(String account, String password, int accountType)
    {
        this.account = account;
        this.password = password;
        this.accountType = accountType;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqUserLogin t = (ReqUserLogin) o;
        return (
            com.qq.taf.jce.JceUtil.equals(account, t.account) && 
            com.qq.taf.jce.JceUtil.equals(password, t.password) && 
            com.qq.taf.jce.JceUtil.equals(accountType, t.accountType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != account)
        {
            _os.write(account, 0);
        }
        if (null != password)
        {
            _os.write(password, 1);
        }
        _os.write(accountType, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.account =  _is.readString(0, false);
        this.password =  _is.readString(1, false);
        this.accountType = (int) _is.read(accountType, 2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(account, "account");
        _ds.display(password, "password");
        _ds.display(accountType, "accountType");
    }

}

