// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ResGetSubedKeywords extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ResGetSubedKeywords";
    }

    public String fullClassName()
    {
        return "zhi_xun.ResGetSubedKeywords";
    }

    public int code = 0;

    public java.util.ArrayList<String> keywords = null;

    public int getCode()
    {
        return code;
    }

    public void  setCode(int code)
    {
        this.code = code;
    }

    public java.util.ArrayList<String> getKeywords()
    {
        return keywords;
    }

    public void  setKeywords(java.util.ArrayList<String> keywords)
    {
        this.keywords = keywords;
    }

    public ResGetSubedKeywords()
    {
    }

    public ResGetSubedKeywords(int code, java.util.ArrayList<String> keywords)
    {
        this.code = code;
        this.keywords = keywords;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ResGetSubedKeywords t = (ResGetSubedKeywords) o;
        return (
            com.qq.taf.jce.JceUtil.equals(code, t.code) && 
            com.qq.taf.jce.JceUtil.equals(keywords, t.keywords) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(code, 0);
        if (null != keywords)
        {
            _os.write(keywords, 1);
        }
    }

    static java.util.ArrayList<String> cache_keywords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.code = (int) _is.read(code, 0, false);
        if(null == cache_keywords)
        {
            cache_keywords = new java.util.ArrayList<String>();
            String __var_8 = "";
            ((java.util.ArrayList<String>)cache_keywords).add(__var_8);
        }
        this.keywords = (java.util.ArrayList<String>) _is.read(cache_keywords, 1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(code, "code");
        _ds.display(keywords, "keywords");
    }

}

