// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package zhi_xun;

public final class ResUserLogin extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ResUserLogin";
    }

    public String fullClassName()
    {
        return "zhi_xun.ResUserLogin";
    }

    public int code = 0;

    public zhi_xun.SessionInfo sessionInfo = null;

    public int getCode()
    {
        return code;
    }

    public void  setCode(int code)
    {
        this.code = code;
    }

    public zhi_xun.SessionInfo getSessionInfo()
    {
        return sessionInfo;
    }

    public void  setSessionInfo(zhi_xun.SessionInfo sessionInfo)
    {
        this.sessionInfo = sessionInfo;
    }

    public ResUserLogin()
    {
    }

    public ResUserLogin(int code, zhi_xun.SessionInfo sessionInfo)
    {
        this.code = code;
        this.sessionInfo = sessionInfo;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ResUserLogin t = (ResUserLogin) o;
        return (
            com.qq.taf.jce.JceUtil.equals(code, t.code) && 
            com.qq.taf.jce.JceUtil.equals(sessionInfo, t.sessionInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(code, 0);
        if (null != sessionInfo)
        {
            _os.write(sessionInfo, 1);
        }
    }

    static zhi_xun.SessionInfo cache_sessionInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.code = (int) _is.read(code, 0, false);
        if(null == cache_sessionInfo)
        {
            cache_sessionInfo = new zhi_xun.SessionInfo();
        }
        this.sessionInfo = (zhi_xun.SessionInfo) _is.read(cache_sessionInfo, 1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(code, "code");
        _ds.display(sessionInfo, "sessionInfo");
    }

}

