// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ClientNewsSummaryHolder
{
    public ClientNewsSummaryHolder()
    {
    }
    public ClientNewsSummaryHolder(ClientNewsSummary value)
    {
        this.value = value;
    }

    public ClientNewsSummary value;
}
