// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ClientNewsSummary extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ClientNewsSummary";
    }

    public String fullClassName()
    {
        return "zhi_xun.ClientNewsSummary";
    }

    public int id = 0;

    public String title = "";

    public String pubDate = "";

    public java.util.ArrayList<String> img = null;

    public String summaryDescription = "";

    public String author = "";

    public String link = "";

    public boolean isCollect = true;

    public int categoryId = 0;
    
    public int itemStatus = 0;

    public java.util.ArrayList<String> keywords = null;

    public int getId()
    {
        return id;
    }

    public int getItemStatus() {
		return itemStatus;
	}

	public void setItemStatus(int itemStatus) {
		this.itemStatus = itemStatus;
	}

	public void  setId(int id)
    {
        this.id = id;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getPubDate()
    {
        return pubDate;
    }

    public void  setPubDate(String pubDate)
    {
        this.pubDate = pubDate;
    }

    public java.util.ArrayList<String> getImg()
    {
        return img;
    }

    public void  setImg(java.util.ArrayList<String> img)
    {
        this.img = img;
    }

    public String getSummaryDescription()
    {
        return summaryDescription;
    }

    public void  setSummaryDescription(String summaryDescription)
    {
        this.summaryDescription = summaryDescription;
    }

    public String getAuthor()
    {
        return author;
    }

    public void  setAuthor(String author)
    {
        this.author = author;
    }

    public String getLink()
    {
        return link;
    }

    public void  setLink(String link)
    {
        this.link = link;
    }

    public boolean getIsCollect()
    {
        return isCollect;
    }

    public void  setIsCollect(boolean isCollect)
    {
        this.isCollect = isCollect;
    }

    public int getCategoryId()
    {
        return categoryId;
    }

    public void  setCategoryId(int categoryId)
    {
        this.categoryId = categoryId;
    }

    public java.util.ArrayList<String> getKeywords()
    {
        return keywords;
    }

    public void  setKeywords(java.util.ArrayList<String> keywords)
    {
        this.keywords = keywords;
    }

    public ClientNewsSummary()
    {
    }

    public ClientNewsSummary(int id, String title, String pubDate, java.util.ArrayList<String> img, String summaryDescription, String author, String link, boolean isCollect, int categoryId, java.util.ArrayList<String> keywords)
    {
        this.id = id;
        this.title = title;
        this.pubDate = pubDate;
        this.img = img;
        this.summaryDescription = summaryDescription;
        this.author = author;
        this.link = link;
        this.isCollect = isCollect;
        this.categoryId = categoryId;
        this.keywords = keywords;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ClientNewsSummary t = (ClientNewsSummary) o;
        return (
            com.qq.taf.jce.JceUtil.equals(id, t.id) && 
            com.qq.taf.jce.JceUtil.equals(title, t.title) && 
            com.qq.taf.jce.JceUtil.equals(pubDate, t.pubDate) && 
            com.qq.taf.jce.JceUtil.equals(img, t.img) && 
            com.qq.taf.jce.JceUtil.equals(summaryDescription, t.summaryDescription) && 
            com.qq.taf.jce.JceUtil.equals(author, t.author) && 
            com.qq.taf.jce.JceUtil.equals(link, t.link) && 
            com.qq.taf.jce.JceUtil.equals(isCollect, t.isCollect) && 
            com.qq.taf.jce.JceUtil.equals(categoryId, t.categoryId) && 
            com.qq.taf.jce.JceUtil.equals(keywords, t.keywords) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(title, 1);
        _os.write(pubDate, 2);
        _os.write(img, 3);
        _os.write(summaryDescription, 4);
        _os.write(author, 5);
        _os.write(link, 6);
        _os.write(isCollect, 7);
        _os.write(categoryId, 8);
        _os.write(keywords, 9);
    }

    static java.util.ArrayList<String> cache_img;
    static java.util.ArrayList<String> cache_keywords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (int) _is.read(id, 0, true);
        this.title =  _is.readString(1, true);
        this.pubDate =  _is.readString(2, true);
        if(null == cache_img)
        {
            cache_img = new java.util.ArrayList<String>();
            String __var_1 = "";
            ((java.util.ArrayList<String>)cache_img).add(__var_1);
        }
        this.img = (java.util.ArrayList<String>) _is.read(cache_img, 3, true);
        this.summaryDescription =  _is.readString(4, true);
        this.author =  _is.readString(5, true);
        this.link =  _is.readString(6, true);
        this.isCollect = (boolean) _is.read(isCollect, 7, true);
        this.categoryId = (int) _is.read(categoryId, 8, true);
        if(null == cache_keywords)
        {
            cache_keywords = new java.util.ArrayList<String>();
            String __var_2 = "";
            ((java.util.ArrayList<String>)cache_keywords).add(__var_2);
        }
        this.keywords = (java.util.ArrayList<String>) _is.read(cache_keywords, 9, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(title, "title");
        _ds.display(pubDate, "pubDate");
        _ds.display(img, "img");
        _ds.display(summaryDescription, "summaryDescription");
        _ds.display(author, "author");
        _ds.display(link, "link");
        _ds.display(isCollect, "isCollect");
        _ds.display(categoryId, "categoryId");
        _ds.display(keywords, "keywords");
    }

}

