// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************
package com.iory.zhixun.jce;

public final class NewsContentHolder
{
    public NewsContentHolder()
    {
    }
    public NewsContentHolder(NewsContent value)
    {
        this.value = value;
    }

    public NewsContent value;
}
