// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class NewsSummary extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.NewsSummary";
    }

    public String fullClassName()
    {
        return "zhi_xun.NewsSummary";
    }

    public int id = 0;

    public String title = "";

    public String publicDate = "";

    public java.util.ArrayList<String> img = null;

    public String summary = "";

    public String author = "";

    public String fromSource = "";

    public boolean isCollect = true;

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getPublicDate()
    {
        return publicDate;
    }

    public void  setPublicDate(String publicDate)
    {
        this.publicDate = publicDate;
    }

    public java.util.ArrayList<String> getImg()
    {
        return img;
    }

    public void  setImg(java.util.ArrayList<String> img)
    {
        this.img = img;
    }

    public String getSummary()
    {
        return summary;
    }

    public void  setSummary(String summary)
    {
        this.summary = summary;
    }

    public String getAuthor()
    {
        return author;
    }

    public void  setAuthor(String author)
    {
        this.author = author;
    }

    public String getFromSource()
    {
        return fromSource;
    }

    public void  setFromSource(String fromSource)
    {
        this.fromSource = fromSource;
    }

    public boolean getIsCollect()
    {
        return isCollect;
    }

    public void  setIsCollect(boolean isCollect)
    {
        this.isCollect = isCollect;
    }

    public NewsSummary()
    {
    }

    public NewsSummary(int id, String title, String publicDate, java.util.ArrayList<String> img, String summary, String author, String fromSource, boolean isCollect)
    {
        this.id = id;
        this.title = title;
        this.publicDate = publicDate;
        this.img = img;
        this.summary = summary;
        this.author = author;
        this.fromSource = fromSource;
        this.isCollect = isCollect;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        NewsSummary t = (NewsSummary) o;
        return (
            com.qq.taf.jce.JceUtil.equals(id, t.id) && 
            com.qq.taf.jce.JceUtil.equals(title, t.title) && 
            com.qq.taf.jce.JceUtil.equals(publicDate, t.publicDate) && 
            com.qq.taf.jce.JceUtil.equals(img, t.img) && 
            com.qq.taf.jce.JceUtil.equals(summary, t.summary) && 
            com.qq.taf.jce.JceUtil.equals(author, t.author) && 
            com.qq.taf.jce.JceUtil.equals(fromSource, t.fromSource) && 
            com.qq.taf.jce.JceUtil.equals(isCollect, t.isCollect) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(title, 1);
        _os.write(publicDate, 2);
        _os.write(img, 3);
        _os.write(summary, 4);
        _os.write(author, 5);
        _os.write(fromSource, 6);
        _os.write(isCollect, 7);
    }

    static java.util.ArrayList<String> cache_img;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (int) _is.read(id, 0, true);
        this.title =  _is.readString(1, true);
        this.publicDate =  _is.readString(2, true);
        if(null == cache_img)
        {
            cache_img = new java.util.ArrayList<String>();
            String __var_1 = "";
            ((java.util.ArrayList<String>)cache_img).add(__var_1);
        }
        this.img = (java.util.ArrayList<String>) _is.read(cache_img, 3, true);
        this.summary =  _is.readString(4, true);
        this.author =  _is.readString(5, true);
        this.fromSource =  _is.readString(6, true);
        this.isCollect = (boolean) _is.read(isCollect, 7, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(title, "title");
        _ds.display(publicDate, "publicDate");
        _ds.display(img, "img");
        _ds.display(summary, "summary");
        _ds.display(author, "author");
        _ds.display(fromSource, "fromSource");
        _ds.display(isCollect, "isCollect");
    }

}

