// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class NewsContent extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.NewsContent";
    }

    public String fullClassName()
    {
        return "zhi_xun.NewsContent";
    }

    public int id = 0;

    public String content = "";

    public java.util.ArrayList<String> keywords = null;

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public java.util.ArrayList<String> getKeywords()
    {
        return keywords;
    }

    public void  setKeywords(java.util.ArrayList<String> keywords)
    {
        this.keywords = keywords;
    }

    public NewsContent()
    {
    }

    public NewsContent(int id, String content, java.util.ArrayList<String> keywords)
    {
        this.id = id;
        this.content = content;
        this.keywords = keywords;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        NewsContent t = (NewsContent) o;
        return (
            com.qq.taf.jce.JceUtil.equals(id, t.id) && 
            com.qq.taf.jce.JceUtil.equals(content, t.content) && 
            com.qq.taf.jce.JceUtil.equals(keywords, t.keywords) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(content, 1);
        _os.write(keywords, 3);
    }

    static java.util.ArrayList<String> cache_keywords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (int) _is.read(id, 0, true);
        this.content =  _is.readString(1, true);
        if(null == cache_keywords)
        {
            cache_keywords = new java.util.ArrayList<String>();
            String __var_2 = "";
            ((java.util.ArrayList<String>)cache_keywords).add(__var_2);
        }
        this.keywords = (java.util.ArrayList<String>) _is.read(cache_keywords, 3, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(content, "content");
        _ds.display(keywords, "keywords");
    }

}

