// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ReqGetNewsList extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "com.iory.zhixun.jce.ReqGetNewsList";
    }

    public String fullClassName()
    {
        return "com.iory.zhixun.jce.ReqGetNewsList";
    }

    public com.iory.zhixun.jce.SessionInfo sessionInfo = null;

    public int lastNewsId = 0;

    public int categoryId = 0;

    public com.iory.zhixun.jce.SessionInfo getSessionInfo()
    {
        return sessionInfo;
    }

    public void  setSessionInfo(com.iory.zhixun.jce.SessionInfo sessionInfo)
    {
        this.sessionInfo = sessionInfo;
    }

    public int getLastNewsId()
    {
        return lastNewsId;
    }

    public void  setLastNewsId(int lastNewsId)
    {
        this.lastNewsId = lastNewsId;
    }

    public int getCategoryId()
    {
        return categoryId;
    }

    public void  setCategoryId(int categoryId)
    {
        this.categoryId = categoryId;
    }

    public ReqGetNewsList()
    {
    }

    public ReqGetNewsList(com.iory.zhixun.jce.SessionInfo sessionInfo, int lastNewsId, int categoryId)
    {
        this.sessionInfo = sessionInfo;
        this.lastNewsId = lastNewsId;
        this.categoryId = categoryId;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqGetNewsList t = (ReqGetNewsList) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sessionInfo, t.sessionInfo) && 
            com.qq.taf.jce.JceUtil.equals(lastNewsId, t.lastNewsId) && 
            com.qq.taf.jce.JceUtil.equals(categoryId, t.categoryId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sessionInfo, 0);
        _os.write(lastNewsId, 1);
        _os.write(categoryId, 2);
    }

    static com.iory.zhixun.jce.SessionInfo cache_sessionInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_sessionInfo)
        {
            cache_sessionInfo = new com.iory.zhixun.jce.SessionInfo();
        }
        this.sessionInfo = (com.iory.zhixun.jce.SessionInfo) _is.read(cache_sessionInfo, 0, true);
        this.lastNewsId = (int) _is.read(lastNewsId, 1, true);
        this.categoryId = (int) _is.read(categoryId, 2, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sessionInfo, "sessionInfo");
        _ds.display(lastNewsId, "lastNewsId");
        _ds.display(categoryId, "categoryId");
    }

}

