// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ReqGetNewsContentHolder
{
    public ReqGetNewsContentHolder()
    {
    }
    public ReqGetNewsContentHolder(ReqGetNewsContent value)
    {
        this.value = value;
    }

    public ReqGetNewsContent value;
}
