// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ReqSubKeywords extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ReqSubKeywords";
    }

    public String fullClassName()
    {
        return "zhi_xun.ReqSubKeywords";
    }

    public int uin = 0;

    public java.util.ArrayList<String> keywords = null;

    public int getUin()
    {
        return uin;
    }

    public void  setUin(int uin)
    {
        this.uin = uin;
    }

    public java.util.ArrayList<String> getKeywords()
    {
        return keywords;
    }

    public void  setKeywords(java.util.ArrayList<String> keywords)
    {
        this.keywords = keywords;
    }

    public ReqSubKeywords()
    {
    }

    public ReqSubKeywords(int uin, java.util.ArrayList<String> keywords)
    {
        this.uin = uin;
        this.keywords = keywords;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ReqSubKeywords t = (ReqSubKeywords) o;
        return (
            com.qq.taf.jce.JceUtil.equals(uin, t.uin) && 
            com.qq.taf.jce.JceUtil.equals(keywords, t.keywords) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(uin, 0);
        _os.write(keywords, 1);
    }

    static java.util.ArrayList<String> cache_keywords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.uin = (int) _is.read(uin, 0, true);
        if(null == cache_keywords)
        {
            cache_keywords = new java.util.ArrayList<String>();
            String __var_4 = "";
            ((java.util.ArrayList<String>)cache_keywords).add(__var_4);
        }
        this.keywords = (java.util.ArrayList<String>) _is.read(cache_keywords, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(uin, "uin");
        _ds.display(keywords, "keywords");
    }

}

