// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResCollectNewsHolder
{
    public ResCollectNewsHolder()
    {
    }
    public ResCollectNewsHolder(ResCollectNews value)
    {
        this.value = value;
    }

    public ResCollectNews value;
}
