// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResCollectNews extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "zhi_xun.ResCollectNews";
    }

    public String fullClassName()
    {
        return "zhi_xun.ResCollectNews";
    }

    public int code = 0;

    public int getCode()
    {
        return code;
    }

    public void  setCode(int code)
    {
        this.code = code;
    }

    public ResCollectNews()
    {
    }

    public ResCollectNews(int code)
    {
        this.code = code;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ResCollectNews t = (ResCollectNews) o;
        return (
            com.qq.taf.jce.JceUtil.equals(code, t.code) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(code, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.code = (int) _is.read(code, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(code, "code");
    }

}

