// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResGetCollectNewsHolder
{
    public ResGetCollectNewsHolder()
    {
    }
    public ResGetCollectNewsHolder(ResGetCollectNews value)
    {
        this.value = value;
    }

    public ResGetCollectNews value;
}
