// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResGetCategories extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "com.iory.zhixun.jce.ResGetCategories";
    }

    public String fullClassName()
    {
        return "com.iory.zhixun.jce.ResGetCategories";
    }

    public int code = 0;

    public java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory> categories = null;

    public int getCode()
    {
        return code;
    }

    public void  setCode(int code)
    {
        this.code = code;
    }

    public java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory> getCategories()
    {
        return categories;
    }

    public void  setCategories(java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory> categories)
    {
        this.categories = categories;
    }

    public ResGetCategories()
    {
    }

    public ResGetCategories(int code, java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory> categories)
    {
        this.code = code;
        this.categories = categories;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ResGetCategories t = (ResGetCategories) o;
        return (
            com.qq.taf.jce.JceUtil.equals(code, t.code) && 
            com.qq.taf.jce.JceUtil.equals(categories, t.categories) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(code, 0);
        _os.write(categories, 1);
    }

    static java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory> cache_categories;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.code = (int) _is.read(code, 0, true);
        if(null == cache_categories)
        {
            cache_categories = new java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory>();
            com.iory.zhixun.jce.ClientNewsCategory __var_5 = new com.iory.zhixun.jce.ClientNewsCategory();
            ((java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory>)cache_categories).add(__var_5);
        }
        this.categories = (java.util.ArrayList<com.iory.zhixun.jce.ClientNewsCategory>) _is.read(cache_categories, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(code, "code");
        _ds.display(categories, "categories");
    }

}

