// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `/home/corey/samba_dir/zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResGetNewsListHolder
{
    public ResGetNewsListHolder()
    {
    }
    public ResGetNewsListHolder(ResGetNewsList value)
    {
        this.value = value;
    }

    public ResGetNewsList value;
}
