// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResGetCollectNews extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "com.iory.zhixun.jce.ResGetCollectNews";
    }

    public String fullClassName()
    {
        return "com.iory.zhixun.jce.ResGetCollectNews";
    }

    public int code = 0;

    public java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary> newsList = null;

    public int getCode()
    {
        return code;
    }

    public void  setCode(int code)
    {
        this.code = code;
    }

    public java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary> getNewsList()
    {
        return newsList;
    }

    public void  setNewsList(java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary> newsList)
    {
        this.newsList = newsList;
    }

    public ResGetCollectNews()
    {
    }

    public ResGetCollectNews(int code, java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary> newsList)
    {
        this.code = code;
        this.newsList = newsList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ResGetCollectNews t = (ResGetCollectNews) o;
        return (
            com.qq.taf.jce.JceUtil.equals(code, t.code) && 
            com.qq.taf.jce.JceUtil.equals(newsList, t.newsList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(code, 0);
        _os.write(newsList, 1);
    }

    static java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary> cache_newsList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.code = (int) _is.read(code, 0, true);
        if(null == cache_newsList)
        {
            cache_newsList = new java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary>();
            com.iory.zhixun.jce.ClientNewsSummary __var_4 = new com.iory.zhixun.jce.ClientNewsSummary();
            ((java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary>)cache_newsList).add(__var_4);
        }
        this.newsList = (java.util.ArrayList<com.iory.zhixun.jce.ClientNewsSummary>) _is.read(cache_newsList, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(code, "code");
        _ds.display(newsList, "newsList");
    }

}

