// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.4 by WSRD Tencent.
// Generated from `zx.jce'
// **********************************************************************

package com.iory.zhixun.jce;

public final class ResRemoveSubedKeywordsHolder
{
    public ResRemoveSubedKeywordsHolder()
    {
    }
    public ResRemoveSubedKeywordsHolder(ResRemoveSubedKeywords value)
    {
        this.value = value;
    }

    public ResRemoveSubedKeywords value;
}
